### ISSUE TITLE
Are there some packages missing?

### ISSUE THREAD

**Issue by amanchuan** [liufly/delayed-memory-update-entnet#3]
hi liufly. In main.py file, lstm_att_con and DataManager would be imported, but there are no file in this repo. Are there some packages missing? Thanks for any help.

**Comment by liufly** [comment]
@revierJ I cannot find any "lstm_att_con" or "DataManager" with a quick in-repository search, can you please provide a bit more info?

**Comment by amanchuan** [comment]
@liufly Sorry, It's my fault, i don't clone the latest repo. Thanks.
